In [6]:
# transpose, inverse

import numpy as np
A = np.array([[1, 1, 1],
              [2, 2, 2]])

print(A.shape)
A

(2, 3)


array([[1, 1, 1],
       [2, 2, 2]])

In [7]:
# transpose
A.T

array([[1, 2],
       [1, 2],
       [1, 2]])

In [23]:
# inverse
# transpose, inverse
# https://www.varsitytutors.com/hotmath/hotmath_help/topics/inverse-matrices
import numpy as np
from numpy import linalg
A = np.array([
              [1., 2.], 
              [3., 4.]
             ])

A
# print(dir(linalg))
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
from numpy.linalg import inv
a = np.array([[1., 2.], 
              [3., 4.]
             ])
ainv = inv(a)