In [1]:
############################
#For skip data preprocessing
############################
import pandas as pd
sample = pd.read_pickle('data.pickle')
sample[:3]

filename chroma_stft         rmse   spectral_centroid  \
0  blues.00000.wav  0.34994322   0.13022463  1784.4204464946633   
0  blues.00001.wav   0.3409832  0.095918424  1529.8353159300755   
0  blues.00002.wav  0.36360285   0.17557304  1552.4819582458863   

   spectral_bandwidth             rolloff    zero_crossing_rate       mfcc1  \
0  2002.6501916232635  3806.4853160373937   0.08306639113293343  -113.59675   
0  2038.6175789692213  3548.8202074363876  0.056044256724071206   -207.5568   
0  1747.1659849613065   3040.514947755418   0.07630074799245357   -90.75439   

       mfcc2       mfcc3  ...    mfcc12      mfcc13     mfcc14      mfcc15  \
0   121.5573  -19.158825  ...  8.810669  -3.6673682   5.751691  -5.1627626   
0  124.00672     8.93056  ...  5.376803  -2.2391195  4.2169633  -6.0122733   
0   140.4599  -29.109964  ...  5.789265   -8.905224   -1.08372   -9.218358   

       mfcc16       mfcc17       mfcc18      mfcc19      mfcc20  style  
0  0.75094783   -1.6919376  -0.40995264  -2.3002088   1.2199285  blues  
0   0.9361094  -0.71653724   0.29387605  -0.2874308   0.5315728  blues  
0    2.455806    -7.726901    -1.815723  -3.4334342  -2.2268214  blues  

[3 rows x 28 columns]

In [2]:
# X, y
# y <-- one-hot encoder or label encoder
# X <-- data type astype('float32')
# standarization(optional)
# train_test_split
# build model with algorithm
# model.fit
# model.score & model.predict

In [12]:
# y 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_raw = sample.iloc[:, -1].values
y = le.fit_transform(y_raw)
y[:3]

array([0, 0, 0])

In [13]:
# X 頭filename　尾style　不要
X = sample.iloc[:, 1:-1].values.astype('float32')
X[:3]

array([[ 3.49943221e-01,  1.30224630e-01,  1.78442041e+03,
         2.00265015e+03,  3.80648535e+03,  8.30663890e-02,
        -1.13596748e+02,  1.21557297e+02, -1.91588249e+01,
         4.23510323e+01, -6.37645817e+00,  1.86188755e+01,
        -1.36979113e+01,  1.53446312e+01, -1.22852669e+01,
         1.09804916e+01, -8.32432461e+00,  8.81066895e+00,
        -3.66736817e+00,  5.75169086e+00, -5.16276264e+00,
         7.50947833e-01, -1.69193757e+00, -4.09952641e-01,
        -2.30020881e+00,  1.21992850e+00],
       [ 3.40983212e-01,  9.59184244e-02,  1.52983533e+03,
         2.03861755e+03,  3.54882031e+03,  5.60442582e-02,
        -2.07556793e+02,  1.24006721e+02,  8.93056011e+00,
         3.58746872e+01,  2.91603684e+00,  2.15237255e+01,
        -8.55470371e+00,  2.33586712e+01, -1.01036167e+01,
         1.19037437e+01, -5.56038809e+00,  5.37680292e+00,
        -2.23911953e+00,  4.21696329e+00, -6.01227331e+00,
         9.36109424e-01, -7.16537237e-01,  2.93876052e-01,
        -2.87

In [25]:
# 加入資料前處理
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_ss = ss.fit_transform(X)

In [26]:
# 分割數據
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_ss, y, test_size=0.2, random_state=42)

In [27]:
# 確認數據種類 & 個數
import numpy as np
np.bincount(y_train)

array([80, 87, 73, 79, 85, 78, 75, 87, 77, 79], dtype=int64)

In [35]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
model = ExtraTreesClassifier()
# model = MLPClassifier()
# model = RandomForestClassifier()
# model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

ExtraTreesClassifier()

In [37]:
model.score(X_train, y_train), model.score(X_test, y_test)
# (0.99875, 0.645) wo standardization
# (0.99875, 0.635) w standardization

(0.99875, 0.64)