In [1]:
!pip install jieba==0

ERROR: Could not find a version that satisfies the requirement jieba==0 (from versions: 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.26.1, 0.27, 0.28, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.29, 0.29.1, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.36.2, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.42.1)
ERROR: No matching distribution found for jieba==0


In [4]:
import jieba
jieba.__version__

'0.42.1'

In [6]:
# print(dir(jieba))
jieba.cut_for_search?

In [3]:
import jieba
list(jieba.cut(sentence = '這是第一篇文章.'))

['這是', '第一篇', '文章', '.']

In [9]:
import jieba

seg_list = jieba.cut("小明碩士畢業于台灣大學電機所，後在日本京都大學深造", cut_all=True)
print("Full Mode: " + ", ".join(seg_list))  # 全模式
seg_list = jieba.cut("小明碩士畢業于台灣大學電機所，後在日本京都大學深造", cut_all=False)
print("Default Mode: " + ", ".join(seg_list))  # 精確模式

seg_list = jieba.cut_for_search("小明碩士畢業于台灣大學電機所，後在日本京都大學深造")  # 搜索引擎模式
print(", ".join(seg_list))

Full Mode: 小, 明, 碩, 士, 畢, 業, 于, 台, 灣, 大, 學, 電, 機, 所, ，, 後, 在, 日本, 京都, 大, 學, 深造
Default Mode: 小明, 碩士, 畢業于, 台灣, 大學, 電機, 所, ，, 後, 在, 日本, 京都, 大學, 深造
小明, 碩士, 畢業于, 台灣, 大學, 電機, 所, ，, 後, 在, 日本, 京都, 大學, 深造


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
corpus = [
    '這是第一篇文章',
    '這文章是第二篇',
    '並且這是第三篇',
    '這是第一篇文章嗎',
]
words = []
for c in corpus :
    words.extend( list(jieba.cut(sentence = c )) )
np.unique( words )

array(['並且', '嗎', '文章', '是', '第一篇', '第三篇', '第二篇', '這', '這是'], dtype='<U3')

In [7]:
# 手動轉換成 
# Sentence to vector 
#  [[0 1 1 1 0 0 1 0 1]
#  [0 2 0 1 0 1 1 0 1]
#  [1 0 0 1 1 0 1 1 1]
#  [0 1 1 1 0 0 1 0 1]]

list(jieba.cut(sentence = '這是第一篇文章 Microsoft windows 10' ))

['這是', '第一篇', '文章', ' ', 'Microsoft', ' ', 'windows', ' ', '10']

In [5]:
# 思考
# ['這是', '第一篇', '文章'] 
# ['並且', '嗎', '文章', '是', '第一篇', '第三篇', '第二篇', '這', '這是']
# [0    ,    0,      1,    0,        1,       0,        0,   0,      1]
zh_all = np.unique( words )
zh_cv = np.zeros([4,9]).astype('int')
###############################################
#字頻分析表
##############################################
# 從文章中取出 每一 kk=序號， vv=每一條文章內容
for kk,vv in enumerate(corpus):
    # 針對 vv 每一個文章內容去切字
    for v in list(jieba.cut(sentence = vv )):
        # 針對 每一個單字 進行 轉換 1 
        pos = np.where(zh_all == v)
        zh_cv[kk, pos] = 1
zh_cv 

array([[0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 1]])

In [10]:
# enumerate
for i in enumerate(range(5, 8)):
    print(i)

(0, 5)
(1, 6)
(2, 7)


In [36]:
zh_cv

array([[0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 1]])

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(zh_cv[0].reshape(1,-1), zh_cv).ravel()

array([1.        , 0.28867513, 0.33333333, 0.8660254 ])

In [ ]:
# corpus = [
#     '這是第一篇文章',
#     '這文章是第二篇',
#     '並且這是第三篇',
#     '這是第一篇文章嗎',
# ]

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
corpus = [
    '這是第一篇文章',
    '這文章是第二篇',
    '並且這是第三篇',
    '這是第一篇文章嗎',
]
words = []
for c in corpus :
    words.append( ' '.join(list(jieba.cut(sentence = c ))) )

print(words)

['這是 第一篇 文章', '這 文章 是 第二篇', '並且 這是 第三篇', '這是 第一篇 文章 嗎']


In [8]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(zh_cv)
tfidf.toarray().shape # 四篇文章 所有的單字 
tfidf.toarray() # 該部分類似 CountVectorizer() 顯示單字出現的頻率，加上權重

array([[0.        , 0.        , 0.53256952, 0.        , 0.65782931,
        0.        , 0.        , 0.        , 0.53256952],
       [0.        , 0.        , 0.34578314, 0.5417361 , 0.        ,
        0.        , 0.5417361 , 0.5417361 , 0.        ],
       [0.64450299, 0.        , 0.        , 0.        , 0.        ,
        0.64450299, 0.        , 0.        , 0.41137791],
       [0.        , 0.64065543, 0.40892206, 0.        , 0.5051001 ,
        0.        , 0.        , 0.        , 0.40892206]])

In [9]:
base = 3
similarity_subject = np.array(cosine_similarity(tfidf[base], tfidf)).ravel()
similarity_subject

array([0.76782851, 0.14139835, 0.1682215 , 1.        ])