In [1]:
import pandas as pd
data = pd.read_csv('Lemonade.csv')
data[:3]

Date      Day  Temperature  Rainfall  Flyers  Price  Sales
0  01/01/2017   Sunday         27.0      2.00      15    0.3     10
1  02/01/2017   Monday         28.9      1.33      15    0.3     13
2  03/01/2017  Tuesday         34.5      1.33      27    0.3     15

In [2]:
data.Day.value_counts().sort_index()

Friday       52
Monday       52
Saturday     52
Sunday       53
Thursday     52
Tuesday      52
Wednesday    52
Name: Day, dtype: int64

In [3]:
# data.Day : label-encoder  
#            sklearn.labelencoder
# data.Day : onehot-encoder 0 0 0 1 0 0 0
#                           0 1 0 0 0 0 0 
#            pandas.get_dummy

In [4]:
# label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(data.Day)
le.transform(data.Day)

array([3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,
       3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,

In [5]:
# one-hot encoder
from keras.utils import np_utils
ohe = np_utils.to_categorical( le.transform(data.Day) ).astype('int')
ohe[:3]

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0]])

In [6]:
# Machine Learning : merge
import numpy as np
X = np.hstack((ohe, data.iloc[:, 2:-1].values))
y = data.iloc[:, -1]
X[:3]

array([[ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  , 27.  ,  2.  ,
        15.  ,  0.3 ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 28.9 ,  1.33,
        15.  ,  0.3 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 34.5 ,  1.33,
        27.  ,  0.3 ]])

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [8]:
model.score(X, y) * 100

98.2316117711005