In [ ]:
# https://machinelearningmastery.com/regression-tutorial-keras-deep-learning-library-python/


In [ ]:
import pandas as pd
data = pd.read_csv('Lemonade.csv')
data[:3]

Date      Day  Temperature  Rainfall  Flyers  Price  Sales
0  01/01/2017   Sunday         27.0      2.00      15    0.3     10
1  02/01/2017   Monday         28.9      1.33      15    0.3     13
2  03/01/2017  Tuesday         34.5      1.33      27    0.3     15

Date      Day  Temperature  Rainfall  Flyers  Price  Sales
0  01/01/2017   Sunday         27.0      2.00      15    0.3     10
1  02/01/2017   Monday         28.9      1.33      15    0.3     13
2  03/01/2017  Tuesday         34.5      1.33      27    0.3     15

In [ ]:
data.Day.value_counts().sort_index()

Friday       52
Monday       52
Saturday     52
Sunday       53
Thursday     52
Tuesday      52
Wednesday    52
Name: Day, dtype: int64

Friday       52
Monday       52
Saturday     52
Sunday       53
Thursday     52
Tuesday      52
Wednesday    52
Name: Day, dtype: int64

In [ ]:
# data.Day : label-encoder  
#            sklearn.labelencoder
# data.Day : onehot-encoder 0 0 0 1 0 0 0
#                           0 1 0 0 0 0 0 
#            pandas.get_dummy

In [ ]:
# label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(data.Day)
le.transform(data.Day)

array([3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,
       3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,

array([3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,
       3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,

In [ ]:
# Machine Learning
import numpy as np
X = np.hstack((le.fit_transform(data.Day).reshape(-1, 1), data.iloc[:, 2:-1].values))
y = data.iloc[:, -1]
X[:3]

array([[ 3.  , 27.  ,  2.  , 15.  ,  0.3 ],
       [ 1.  , 28.9 ,  1.33, 15.  ,  0.3 ],
       [ 5.  , 34.5 ,  1.33, 27.  ,  0.3 ]])

array([[ 3.  , 27.  ,  2.  , 15.  ,  0.3 ],
       [ 1.  , 28.9 ,  1.33, 15.  ,  0.3 ],
       [ 5.  , 34.5 ,  1.33, 27.  ,  0.3 ]])

In [ ]:
# Keras Deep Learning
import keras
from keras.layers import Dense, Activation #神經層
model = keras.models.Sequential()
# Add Input layer, 隱藏層(hidden layer) 有 256個輸出變數
model.add(Dense(units=256, input_dim=5, 
                kernel_initializer='normal', activation='relu'))             # input + hidder layer
# model.add(Dense(units=128, kernel_initializer='normal', activation='relu'))  # hidder layer
# model.add(Dense(units=64, kernel_initializer='normal', activation='relu'))  # hidder layer
model.add(Dense(units=1, kernel_initializer='normal'))# Add output layer

# 編譯: 選擇損失函數、優化方法及成效衡量方式
model.compile(loss='mean_squared_error', optimizer='adam')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 256)               1536      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 257       
Total params: 1,793
Trainable params: 1,793
Non-trainable params: 0
_________________________________________________________________
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 256)               1536      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 257       
Total params: 1,793
Trainable params: 1,793
Non-trainable params: 0
_________________________________________________________________


In [ ]:
train_history = model.fit(x=X, 
                          y=y, 
                          validation_split=0.2, 
                          epochs=10, 
                          batch_size=5, 
                          verbose=2)   # 0 1 2

Epoch 1/10
Epoch 1/10
59/59 - 2s - loss: 212.4561 - val_loss: 5.6424
59/59 - 2s - loss: 212.4561 - val_loss: 5.6424
Epoch 2/10
Epoch 2/10
59/59 - 0s - loss: 3.9111 - val_loss: 2.3183
59/59 - 0s - loss: 3.9111 - val_loss: 2.3183
Epoch 3/10
Epoch 3/10
59/59 - 1s - loss: 3.1327 - val_loss: 2.3142
59/59 - 1s - loss: 3.1327 - val_loss: 2.3142
Epoch 4/10
Epoch 4/10
59/59 - 0s - loss: 2.5870 - val_loss: 1.7791
59/59 - 0s - loss: 2.5870 - val_loss: 1.7791
Epoch 5/10
Epoch 5/10
59/59 - 0s - loss: 2.2870 - val_loss: 1.6410
59/59 - 0s - loss: 2.2870 - val_loss: 1.6410
Epoch 6/10
Epoch 6/10
59/59 - 0s - loss: 1.8616 - val_loss: 1.4206
59/59 - 0s - loss: 1.8616 - val_loss: 1.4206
Epoch 7/10
Epoch 7/10
59/59 - 0s - loss: 1.6132 - val_loss: 1.3850
59/59 - 0s - loss: 1.6132 - val_loss: 1.3850
Epoch 8/10
Epoch 8/10
59/59 - 0s - loss: 1.3544 - val_loss: 1.1903
59/59 - 0s - loss: 1.3544 - val_loss: 1.1903
Epoch 9/10
Epoch 9/10
59/59 - 0s - loss: 1.1522 - val_loss: 1.3026
59/59 - 0s - loss: 1.1522 - val_l

In [ ]:
model.predict(X)

array([[11.489847 ],
       [12.15974  ],
       [14.92148  ],
       [18.578083 ],
       [18.210724 ],
       [11.297343 ],
       [13.908068 ],
       [16.104097 ],
       [15.903465 ],
       [18.589634 ],
       [13.9894495],
       [15.673705 ],
       [15.639924 ],
       [18.322002 ],
       [18.604248 ],
       [13.322528 ],
       [14.045902 ],
       [18.366943 ],
       [18.330484 ],
       [13.472281 ],
       [14.948425 ],
       [16.843142 ],
       [15.947594 ],
       [12.316547 ],
       [13.865556 ],
       [14.909168 ],
       [17.521372 ],
       [14.400904 ],
       [15.190734 ],
       [17.026192 ],
       [17.878445 ],
       [18.366203 ],
       [21.18982  ],
       [20.772896 ],
       [24.287512 ],
       [19.309954 ],
       [18.937569 ],
       [22.272484 ],
       [21.943039 ],
       [18.82198  ],
       [21.477343 ],
       [21.6966   ],
       [23.637663 ],
       [19.804657 ],
       [20.319118 ],
       [21.83112  ],
       [19.949038 ],
       [17.25

array([[11.489847 ],
       [12.15974  ],
       [14.92148  ],
       [18.578083 ],
       [18.210724 ],
       [11.297343 ],
       [13.908068 ],
       [16.104097 ],
       [15.903465 ],
       [18.589634 ],
       [13.9894495],
       [15.673705 ],
       [15.639924 ],
       [18.322002 ],
       [18.604248 ],
       [13.322528 ],
       [14.045902 ],
       [18.366943 ],
       [18.330484 ],
       [13.472281 ],
       [14.948425 ],
       [16.843142 ],
       [15.947594 ],
       [12.316547 ],
       [13.865556 ],
       [14.909168 ],
       [17.521372 ],
       [14.400904 ],
       [15.190734 ],
       [17.026192 ],
       [17.878445 ],
       [18.366203 ],
       [21.18982  ],
       [20.772896 ],
       [24.287512 ],
       [19.309954 ],
       [18.937569 ],
       [22.272484 ],
       [21.943039 ],
       [18.82198  ],
       [21.477343 ],
       [21.6966   ],
       [23.637663 ],
       [19.804657 ],
       [20.319118 ],
       [21.83112  ],
       [19.949038 ],
       [17.25