In [2]:
import numpy as np
np.random.uniform(-1.0, 1.0, size=[16, 100])

array([[ 0.12098902,  0.03837097,  0.24365545, ..., -0.20079804,
        -0.94396701,  0.21306926],
       [-0.11399082, -0.80423534,  0.29529573, ..., -0.75450192,
         0.71127731,  0.13940675],
       [-0.41759604, -0.22236333, -0.95764196, ...,  0.11746864,
         0.97030029,  0.29601996],
       ...,
       [ 0.08188286,  0.14916998,  0.69591985, ...,  0.43633264,
         0.62096481,  0.58182066],
       [-0.42604857, -0.3929608 , -0.51979935, ..., -0.53650708,
        -0.31814922,  0.30495145],
       [ 0.49438988,  0.13019485,  0.03735854, ...,  0.56966772,
        -0.08299256,  0.98212804]])

In [3]:
np.random.randint(0, 50000, size=256)

array([45102,  7622, 37876, 45843, 11500,  2514, 47046, 36692,  2718,
        2682, 18649,  6885, 31138, 36195, 19549, 34748, 14151,  7848,
       18647,  2473,  8909, 35000, 24108, 12755, 46929,  8854, 33445,
       24110,  1314,  6573, 42680, 46711, 43977, 38470, 43054, 26740,
       45768, 18218, 44947,  2506, 48258, 10298, 44596,  3612,  5895,
       21769, 27218, 15043, 44679, 27874, 45397, 29611,  6265, 17006,
       42661,  1144, 29374,   814, 38056, 35921,  3759, 40899, 38044,
       46881, 14377, 40925, 18954,  8808,  6194, 21588,  2553, 49430,
       26295, 26220,  7184, 35658, 39651, 31612, 15524, 44792,  6093,
         171,  2827, 32981, 29185, 26079, 42521, 16037, 28906, 18470,
       43115, 45975,  1886, 47815, 25262, 36703, 34378,  3745, 33037,
       11051, 11303, 20309, 46079, 25047, 13195, 34532, 44448, 26126,
        7319, 40876, 33838, 26590,  2499,    50, 38309, 40289, 15525,
       41592, 26800, 26067, 32202, 10100, 26636,  3119, 15783, 20899,
       46390, 17705,

In [13]:
np.random.seed(1234)
a = np.random.randint(1, 6, size=(5, 1))
b = np.random.randint(7, 10, size=(5, 1))
print(a, b)
np.concatenate((a, b))

[[4]
 [5]
 [5]
 [1]
 [2]] [[8]
 [8]
 [9]
 [9]
 [9]]


array([[4],
       [5],
       [5],
       [1],
       [2],
       [8],
       [8],
       [9],
       [9],
       [9]])

In [15]:
np.ones((10, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
np.ones([10, 1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])