In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [2]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris.keys()
X, y = iris.data, iris.target
X[:3], y[:3], y[-3:] # 前後五十兩種花

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([0, 0, 0]),
 array([2, 2, 2]))

In [4]:

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters = {'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'), 
              'C':[1, 2, 3, 4, 5, 10]}

model = LogisticRegression()
clf = GridSearchCV(model, parameters)
clf.fit(X, y)

c:\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\python38\lib\site-packages\sklearn\linear_model\_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\python38\lib\site-packages\sklearn\linear_model\_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
c:\python38\lib\site-packages\sklearn\linear_model\_sag.py:328: ConvergenceWarning: The max

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 10],
                         'solver': ('newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga')})

In [6]:
clf.best_score_, clf.best_params_

(0.9866666666666667, {'C': 1, 'solver': 'saga'})

In [ ]:
# pipeline, k-fold, GridSearchCV
# pipeline, k-fold, voting <-- After found the best estimators from above.....
