In [2]:
!pip install scikit-learn==0

ERROR: Could not find a version that satisfies the requirement scikit-learn==0 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 1.0rc1, 1.0rc2, 1.0)
ERROR: No matching distribution found for scikit-learn==0


In [1]:
import sklearn 
sklearn.__version__

'0.24.2'

In [3]:
colors = ['Red', 'Blue', 'Green', 'Blue']

In [5]:
# one-hot encoding
# 按照字母排序 abcd.....xyz

# ValueError: Expected 2D array, got 1D array instead:
# array=['Red' 'Blue' 'Green' 'Blue'].
# Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(colors)

ValueError: Expected 2D array, got 1D array instead:
array=['Red' 'Blue' 'Green' 'Blue'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [8]:
# one-hot encoding
# 按照字母排序 abcd.....xyz
# <4x3 sparse matrix of type '<class 'numpy.float64'>'
# 	with 4 stored elements in Compressed Sparse Row format>
# Blue = 0 , Green = 1, Red = 2

#         0   1   2

# array([[0., 0., 1.], <--- Red
#        [1., 0., 0.], <--- Blue
#        [0., 1., 0.], <--- Green
#        [1., 0., 0.]])<--- Blue
colors = [['Red'], 
          ['Blue'], 
          ['Green'], 
          ['Blue'] ]
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(colors)
ohe.transform(colors).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [11]:
# TypeError: unhashable type: 'list'
colors = [['Red'], 
          ['Blue'], 
          ['Green'], 
          ['Blue'] ]
import pandas as pd
pd.get_dummies(colors)

TypeError: unhashable type: 'list'

In [23]:
pd.get_dummies?
# List <--> pandas.DataFrame|numpy.array 
# pandas.DataFrame <-- --> numpy.array 

In [24]:
colors = [['Red'], 
          ['Blue'], 
          ['Green'], 
          ['Blue'] ]
import pandas as pd
pd.get_dummies( pd.DataFrame(colors) ).values

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [31]:
#????????????????????????????????????
# Question ????????????????????????????????????
#????????????????????????????????????
# # keras
# colors = [['Red'], 
#           ['Blue'], 
#           ['Green'], 
#           ['Blue'] ]
# ValueError: invalid literal for int() with base 10: 'Red'
import numpy as np
colors = np.array(['Red', 'Blue', 'Green', 'Blue'])
# label encoding 
from keras import  utils
utils.to_categorical( colors )

ValueError: invalid literal for int() with base 10: 'Red'

In [47]:
# Data=文字--> LabelEncoder --> 數字 --> Keras.np_utils.to_caytegorical
from sklearn.preprocessing import LabelEncoder
from keras import  utils
colors = np.array(['Red', 'Blue', 'Green', 'Blue'])
le = LabelEncoder()
utils.to_categorical(le.fit_transform(colors))

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [48]:
# Data=文字--> LabelEncoder --> 數字 --> Keras.np_utils.to_caytegorical
from sklearn.preprocessing import LabelEncoder
from keras import  utils
colors = np.array([2, 0, 1, 0])
le = LabelEncoder()
utils.to_categorical(le.fit_transform(colors))

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
#  以下做法正確 因為人工手動將 Red=2, Green=1, Blue=0

In [32]:
# Keras
import numpy as np
colors = np.array([2, 0, 1, 0])
from keras import  utils
utils.to_categorical( colors )

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [39]:
# Example
from sklearn import datasets
iris = datasets.load_iris()
iris.keys()
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [44]:
species = {0:'setosa', 1:'versicolor', 2:'virginica'}
print(iris.target[:3])
import numpy as np
from keras import  utils
utils.to_categorical( iris.target )[:10]

[0 0 0]


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
colors = np.array(['Red', 'Blue', 'Green', 'Blue'])

In [ ]:
# 資料結構方式處理 one hot encoder
# 取出所有資料 唯一值 + 排序 + 給編碼
# 逐筆取出所有資料，比對 唯一值 + 排序 + 給編碼
#     macthced = 1 else 0